### ISSUE TITLE
Runtime Error: Output with shape [1, 256, 192] doesnt match with the broadcasr shape [3, 256, 192]

### ISSUE THREAD

**Issue by abdullahakmal** [sergeywong/cp-vton#12]
Running on the same dataset, i am getting this error. Any insights would be great. Thank you.

![image](https://user-images.githubusercontent.com/26139749/54275039-74a1dd80-45ab-11e9-925c-6d9ae4b4a55c.png)

**Comment by abdullahakmal** [comment]
downgrading to torchvision 0.2.1 helped me resolving this issue.

**Comment by bob251** [comment]
What if I want to run it with Detectron2 whose torchvision requirement is greater than 0.2.1?
Please provide any alternative. 
Thank you in advance.

**Comment by abdullahakmal** [comment]
Then mostly we need to update the code to use the higher torchvision

**Comment by bob251** [comment]
Thank you so much for this effort. Just one more ques, that by when will it be updated, since I have a deadline to cover.
Thanks.

**Comment by abdullahakmal** [comment]
That i cannt help with. I was also just a user of this.

**Comment by abdullahakmal** [comment]
That i can't help with. I was also just a user of this.
