### ISSUE TITLE
AffineGridGen not used

### ISSUE THREAD

**Issue by solitarysandman** [sergeywong/cp-vton#18]
Hi @sergeywong, 

While AffineGridGen is defined in the _networks_ module, it is not used anywhere for affine warping. How can we incorporate this into TpsGridGen (TPS)?

Where would we need to make the changes in init and forward?

**Comment by VyBui** [comment]
@solitarysandman why is this issue closed?

**Comment by solitarysandman** [comment]
I solved it by tweaking the code using pytorch ST networks tutorials as guide:
https://pytorch.org/tutorials/intermediate/spatial_transformer_tutorial.html

**Comment by solitarysandman** [comment]
Changes are as follows:

1. Change **output_dim** in Feature Regression to 6, because affine has 6 parameters of the shape (2,3)
2. Convert these 6 outputs to the shape of (2,3)
3. Use theta created in step 2 to run affinegridgen to obtain grid
4. Use grid_sample as before to get warped results

**Comment by levindabhi** [comment]
@solitarysandman Sorry if it's a dumb question, but why we need to generate grid through affinegridgen rather than Tpsgridgen?
