### ISSUE TITLE
test question

### ISSUE THREAD

**Issue by Momom52** [sergeywong/cp-vton#3]
Hi, I use your datasets to test your model. But I get this result.I don't know why and how to solve it？
Thank you.

**Comment by Momom52** [comment]
![default](https://user-images.githubusercontent.com/39512686/48296430-d48b5900-e4d1-11e8-9430-6cb5ffdcb6b3.png)

**Comment by Arbi112** [comment]
@Momom52 how did you solved this issue? i am facing the same issue :( 
![screenshot from 2019-02-21 11-35-24](https://user-images.githubusercontent.com/7248059/53141879-ccf94700-35cc-11e9-9921-a23f4208b889.png)
