### ISSUE TITLE
No transformation while running test

### ISSUE THREAD

**Issue by solitarysandman** [sergeywong/cp-vton#6]
Hi @sergeywong, 

As you can see below, there is minimal transformation and warping of the clothing. The cloth is not resized to fit the model either. 

![image](https://user-images.githubusercontent.com/31076890/50272622-4efab180-045e-11e9-8f11-c52eb5ac23a2.png)

Other examples with similar issue:
![image](https://user-images.githubusercontent.com/31076890/50272671-7c475f80-045e-11e9-9c2b-dea87099f6b5.png)

What could be causing the issue here?

**Comment by Momom52** [comment]
hi, I have the same problem as you, have you solved it?

**Comment by Momom52** [comment]
This is my result.
![2018-12-24 23-12-45](https://user-images.githubusercontent.com/39512686/50402425-8b693d00-07d1-11e9-8325-db38a70b64cb.png)

**Comment by solitarysandman** [comment]
@Momom52 I haven't been able to solve it yet. I'm going to try to train the model and test using the updated checkpoint.

**Comment by solitarysandman** [comment]
@Momom52 I retrained the model and used a different checkpoint for testing. The test run gave fair results after that. 

`python test.py --name newtest --stage GMM --workers 4 --datamode test --data_list test_pairs.txt --checkpoint checkpoints/gmm_train_new/step_140000.pth --tensorboard_dir newboard
`

**Comment by b0nl** [comment]
I have the same problem, even when trying with different checkpoints. Any ideas anyone?
