### ISSUE TITLE
changes in tensorboard

### ISSUE THREAD

**Issue by solitarysandman** [sergeywong/cp-vton#8]
How can I change the tensorboard (in train.py/test.py) to show warped cloth overlayed on the person without making the warped cloth or the person transparent?

**Comment by solitarysandman** [comment]
solved this by using a mask of the cloth.

**Comment by Arbi112** [comment]
@solitarysandman  how did you generate warp-mask & warp-cloth? for training TOM

**Comment by solitarysandman** [comment]
Hey @Arbi112 
You can get warp-mask and warp-cloth by:
1. training the GMM module. 
2. run a test on your entire data with a checkpoint of your choice and save all the warp-mask and warp-cloth generated.

**Comment by Arbi112** [comment]
Thank you so much for your quick reply. 
1- Training the GMM Module 
With following commend 
**python train.py --name gmm_train_new --stage GMM --workers 4 --save_count 5000 --shuffle**

i run the test on my test data  as following. How can i save all wrap-mask and wrap-clothe 
![screenshot from 2019-02-20 19-51-11](https://user-images.githubusercontent.com/7248059/53090397-40a64000-354a-11e9-99c9-614321d53e9d.png)

**Comment by Arbi112** [comment]
@solitarysandman Thank you so much for your quick reply. You saved my ass
