### ISSUE TITLE
training on larger images

### ISSUE THREAD

**Issue by solitarysandman** [sergeywong/cp-vton#9]
Hi @sergeywong,

I'm trying to train GMM on images of size 512, 384 - double of what has been used in cp-vton training. What changes would I need to make in _networks.py_? 

I've tried a couple of things but they haven't shown promise:

- changed the number of layers in feature extraction from 3 to 4 (lines 408, 409 in networks.py)
- changed the number of inputs in the linear layer in FeatureRegression to 64*8*6 (line 115 in networks.py)

Can you please let me know how can I train on images of size (512,384)?

Thanks.

**Comment by mr-johnlocke8** [comment]
Would love to know if you solved it, I am trying as well to adjust the model to x2 the size.

**Comment by solitarysandman** [comment]
@mr-johnlocke8 

> changed the number of layers in feature extraction from 3 to 4 (lines 408, 409 in networks.py)

^this worked for me.

**Comment by rishabhdhakarwal** [comment]
@solitarysandman is there any significant difference between the outputs if GMM is trained on larger images as you mentioned.

**Comment by solitarysandman** [comment]
@rishabhdhakarwal not really, no. But increasing the grid size has a beneficial change. Finer warping can be noticed. But increasing grid size comes at a computational cost, so keep that in mind!

**Comment by rishabhdhakarwal** [comment]
@solitarysandman I'm trying to train the model on images of size 4x the current model i.e. 1023 X 768 but I am getting an error 
"missing 2 required positional arguments: 'doc' and 'pos' in the  cp_datasets.py file"
I have made changes in networks.py as you mentioned above, could you help me with this issue?
And also what should I keep the grid size for satisfactory outputs.

Thanks

**Comment by rishabhdhakarwal** [comment]
@solitarysandman  I'm trying to train the model on images of size 4x i.e. 1024 X 768 
What should I keep the grid size for satisfactory outputs?

Thanks

**Comment by solitarysandman** [comment]
@rishabhdhakarwal , You'll have to run multiple experiments, gradually increasing the grid size. Unfortunately, I cannot exactly tune that hyperparameter for you.
